### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by gworkman** [osu-uwrt/riptide_firmware#62]
Change it to uwrt_firmware or maelstrom_firmware. Current name does not reflect the current status of the team and may be confusing

**Comment by blaine141** [comment]
Figure out how to rename without making a new one

**Comment by gworkman** [comment]
It has been renamed. All of the current local repos on everyone's machine will still work just fine with `git push` `git pull` etc, but it is recommended that you change the repo's url to avoid confusion in the future:

`git remote set-url origin new_url`
